#!/bin/sh
#
# Starts LeptonPRU
#

start() {
	printf "Starting LeptonPRU: "
#	umask 077
        modprobe pruss_soc_bus && modprobe pru_rproc && insmod /leptonpru/leptonpru.ko
	[ $? = 0 ] && echo "OK" || echo "FAIL"
}
stop() {
	printf "Stopping LeptonPRU: "
        rmmod leptonpru && rmmod pru_rproc && rmmod pruss_soc_bus
	[ $? = 0 ] && echo "OK" || echo "FAIL"
}
restart() {
	stop
	start
}

case "$1" in
  start)
  	start
	;;
  stop)
  	stop
	;;
  restart|reload)
  	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
